import 'package:portfolio_website/utils/profile_model.dart';

var profiles = [
  Profile(
    name: 'Paing Takhon',
    fullname: 'Sit Ko Paing',
    summary:
        'Paing Takhon was born on 17 July 1996 in Kawthaung, Tanintharyi Region, Myanmar to parent Tun Moe and his wife Khin Kyu. But he grew up in Khamaukgyi. He is the fourth son of six siblings, having an elder brother, two elder sisters and two younger brothers. He graduated high school from Basic Education High School No. 1 Khamaukgyi. In 2014, Paing moved to Yangon to become a model. He is currently studying at University of Distance Education, Yangon, majoring in Psychology. Paing joined John Lwin\'s model training in 2014. Since then, he took professional training in modelling and catwalk. He began his entertainment career as a runway model as part of the John Lwin\'s John International Modeling Agency with countless advertising shows and runways that had been walked on. Then came the offers for TV commercials and then DVD ones. He has appeared in many music videos and as fashion model on magazine cover photos. His hardwork as a model and acting in commercials was noticed by the film industry and soon, movie casting offers came rolling in. In 2016, Paing attended to Indonesia to take part in "Asean Celebrity Explore Quest Malaysia 2016" (ACEQM) together with Nan Su Yati Soe as a representative from Myanmar which is held with famous celebrities and models from South East Asia countries. Paing and Nan Su performed together with U Shwe Yoe and Daw Moe dance at the event. Paing is also a singer and started singing in 2017. He began endeavoring to be able to produce and distribute his first solo album. He launched his debut solo album "Chit Thu" (Lover) on 16 September 2017. Paing donated all his money from selling his albums to orphan children from Ananda Metta orphan school. In 2018, Paing featured on the BuzzFeed "23 Stunning South Asian Men That Are Too Gorgeous For Words". In 2019, Paing also ranked second on The Myanmar Times "Top 10 Actors". Paing is also popular in Thailand. On 3 August 2019, he held a grand fan meeting in Bangkok, Thailand, where a huge crowd of many fans gathered. Paing is an ASEAN Economic Community ambassador. On 21 September 2019, he was appointed as Myanmar\'s tourism ambassador to Thailand by the Myanmar Tourism Marketing Association together with the Myanmar Tourism Federation. In 2020, he was set to star in the upcoming film The Clock: Red Wall directed by Cambodian director Leak Lyda. In December 2021, Paing Takhon was ranked #1 in "The 100 Most Handsome Faces of 2021" list issued by TC Candler.',
    birthdate: '	17.7.1996',
    bloodType: '-',
    height: '180 cm',
    native: 'Myanmar',
    image: 'assets/celebrities/paingtakhon.jpeg',
    instaURL: 'https://www.instagram.com/paing_takhon',
    facebookURL: 'https://www.facebook.com/ptk.offical',
  ),
  Profile(
      name: 'Lisa',
      fullname: 'Pranpriya Manoban',
      summary:
          'Lisa, is a Thai rapper, singer and dancer, based in South Korea. She is a member of Blackpink. Lisa\'s biological parents\' names have not been released to the public, her stepfather is Marco Bruschweiler, a swiss renowned chef, active in Thailand. As a child, Lisa was part of a dance group, that performed shows in her home country before she made a successful audition to the YG Entertainment Competition in 2010 when she was only 13 years old. She ranked first place in the said competition, and was offered by Yang Hyun-suk to become a YG Entertainment trainee, Lisa agreed to the offer. In 2011, she moved to South Korea, to begin her formal training in performing, for her K-pop Idol career, which lasted five years. During this time, she was a member of a dance group named We Zaa Cool along with fellow Thai K-pop Idol trainees, Bambam and Ten. In 2016, she took her stage name of Lisa and became the main dancer, lead rapper, a supporting vocalist and the maknae of K-pop girl group, Blackpink, which debuted on August 8, 2016. Lisa is also the first non-Korean YG Entertainment artist.',
      birthdate: '27.3.1997',
      bloodType: 'O',
      height: '167 cm',
      native: 'Thailand',
      image: 'assets/celebrities/lalisa.jpeg',
      instaURL: 'https://www.instagram.com/lalalalisa_m/?hl=en',
      facebookURL: 'https://www.facebook.com/LisaManobanOFFICIAL/'),
  Profile(
      name: 'Christopher, Chris',
      fullname: 'Chris Hemsworth',
      summary:
          'One of the most talented, most celebrated Hollywood actors, Chris Hemsworth is an all-time favorite actor. He has built his identity by working on innumerable projects for which he has been getting praised by critics and his fans who can’t stop showering love on him. Hemsworth, born 11 August 1983, is an Australian actor. Prior to beginning a career in Hollywood, he gained fame playing Kim Hyde in the Australian television series Home and Away (2004-2007). Thor (2011) and most recently in What If…? Hemsworth is best known for his role as Thor in the Marvel Cinematic Universe. In 2021, he became one of the world’s highest-paid actors',
      birthdate: '11.8.1983',
      bloodType: '',
      height: '191 cm',
      native: 'Australia',
      image: 'assets/celebrities/chris.jpeg',
      instaURL: 'https://www.instagram.com/chrishemsworth/',
      facebookURL: 'https://m.facebook.com/chrishemsworth/'),
  Profile(
      name: 'Emilie Nereng',
      fullname: 'Emilie Marie Nereng',
      summary:
          'Emilie Nereng is a celebrity author. Her genre is Dance/electronic. Her popular songs are Don\'t Talk To Me2010, B.T.B.F. and So Cold2018. The parents of Emilie Marie Nereng are Linda Nereng, Erling Nereng. Emilie Marie Nereng\'s height is 5′ 6″. Voe Blog was created in March 2009 by a Norwegian writer and blogger; by October 2009, it had had 3.5 million hits. ',
      birthdate: '3.11.1995',
      bloodType: '-',
      height: '167.64',
      native: 'Norway',
      image: 'assets/celebrities/emilie.jpeg',
      instaURL: 'https://www.instagram.com/emilienutrition/',
      facebookURL: '-'),
  Profile(
      name: 'V',
      fullname: 'Kim Tae Hyung',
      summary:
          'V was born Kim Tae-hyung on December 30, 1995 in Daegu, South Korea, and grew up in Geochang County. He is the eldest of three children, with a younger brother and sister. V first aspired to be a professional singer in elementary school,and eventually began taking saxophone lessons in early middle school as a means of pursuing the career. V initially became a trainee for Big Hit Entertainment after passing an audition in Daegu. After graduating from Korean Arts High School in 2014, V enrolled in Global Cyber University—he graduated in August 2020 with a major in Broadcasting and Entertainment. As of 2021, he is enrolled at Hanyang Cyber University, pursuing a Master of Business Administration in Advertising and Media.',
      birthdate: '30.12.1995',
      bloodType: 'AB',
      height: '178 cm',
      native: 'South Korea',
      image: 'assets/celebrities/btsV.jpeg',
      instaURL: 'https://www.instagram.com/thv/',
      facebookURL: 'https://www.facebook.com/BTSAegyoTae/')
  // Profile(
  //     name: 'Halima Aden',
  //     summary: '',
  //     birthdate: '',
  //     bloodType: '',
  //     height: '',
  //     native: '',
  //     instaURL: '',
  //     facebookURL: ''),
  // Profile(
  //     name: 'Timothee Chalamet',
  //     summary: '',
  //     birthdate: '',
  //     bloodType: '',
  //     height: '',
  //     native: '',
  //     instaURL: '',
  //     facebookURL: ''),
  // Profile(
  //     name: 'Ivana Alawi',
  //     summary: '',
  //     birthdate: '',
  //     bloodType: '',
  //     height: '',
  //     native: '',
  //     instaURL: '',
  //     facebookURL: ''),
  // Profile(
  //     name: 'Jungkook',
  //     summary: '',
  //     birthdate: '',
  //     bloodType: '',
  //     height: '',
  //     native: '',
  //     instaURL: '',
  //     facebookURL: ''),
  // Profile(
  //     name: 'Nancy Jewel McDonie',
  //     summary: '',
  //     birthdate: '',
  //     bloodType: '',
  //     height: '',
  //     native: '',
  //     instaURL: '',
  //     facebookURL: ''),
];
